### ISSUE TITLE
Concise but cluttered methods

### ISSUE THREAD

**Issue by Rodrigap** [joliejodell/jamming#2]
https://github.com/joliejodell/jamming/blob/04e25f2e60d99096032480ca5036e8c06f88843e/src/Components/App/App.js#L23-L32

Your main methods in App.js all work great and they're really concise, which is awesome! Just remember that sometimes, it makes it harder to read if you smush all your code together too much. I'd recommend adding a single line of blank space between each method, and using multiple lines sometimes when you just use one. Here's how I'd fix this code snippet for legibility:

```
addTrack(track){
  if(!this.state.playlistTracks.find(t=>t.id === track.id)){
    const newState = this.state.playlistTracks.slice(); 
    newState.push(track);

    this.setState({playlistTracks: newState})
  }
  };

  removeTrack(track){
    let newState = this.state.playlistTracks;
    newState = newState.filter(currentTrack => currentTrack.id !== track.id);

    this.setState({playlistTracks:newState});
  };
```

**Comment by joliejodell** [comment]
Thanks, I modified the white space across my .js files
