### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [joliejodell/jamming#4]
Really nice job on this project! Your app is completely functional and well written. I love that you got it properly deployed! It seems like the app logic made sense to you; each of your methods is really concise and all your props are passed perfectly. My only real critique was about the lack of whitespace and some spacing in your components, it's really helpful to add a little bit of whitespace to make things easier to glance over and read. Other than that, great job!

**Comment by joliejodell** [comment]
Thank you for the feedback, I will go back through and add whitespace, I was feeling a bit rushed to get it submitted so I didn't review my readability.
